id = "twilight"
name = "Twilight"
version = "0.0.1"
schema_version = 1
authors = ["waldirbj"]
description = "A direct port of TextMate Twilight theme"
repository = "https://github.com/waldirbertazzijr/zed-twilight"
